# Generated by Django 3.1.1 on 2024-04-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20240404_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='personality',
            name='Age',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='personality',
            name='Gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
